### PR TITLE
docs: added guvi.in to showcase page

### PR DESCRIPTION
**Pull request by JohnPremKumar**
Added the website GUVI homepage which uses QWIK.

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

Added website link of guvi.in which uses QWIK in homepage

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — CHANGES_REQUESTED** [review]
Nice website @JohnPremKumar 
but only the homepage seems to be done with Qwik
Am I correct?

**Comment by gioboa** [comment]
I'm closing this for now because only the homepage is created with Qwik.
feel free to add your thoughts here.

**Comment by JohnPremKumar** [comment]
Yes now home page along with free other pages like privacy policy and refund policy are migrated to qwik.

Other pages are also in development stage will be pushing soon to production.

**Comment by gioboa** [comment]
Nice 👏👏 I love it. May I ask you to submit the PR went you completed the refactoring to Qwik pls?

**Comment by JohnPremKumar** [comment]
Sure

**Pull request closed without merging**
