### PR TITLE
docs: update showcases 

### PR DESCRIPTION
**Pull request by mgp87**
# What is it?
- [x] Docs

# Description

Added our new web page built with qwik framework

# Use cases and why

- Show Lighthouse performance gotten with Qwik
- 
image

Update:
image

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by mgp87** [comment]
Done!
image


> Can you improve the accessibility pls? Screenshot_20240501-144155

**Comment by gioboa** [comment]
Nice :clap: Can you run [build.showcase](https://github.com/QwikDev/qwik/blob/81197c4a025e11287174adfbfcfe87820ae50c01/packages/docs/package.json#L70C12-L70C20) script pls?

**Review by PatrickJS — APPROVED** [review]

**Comment by PatrickJS** [comment]
after you run [build.showcase](https://github.com/QwikDev/qwik/blob/81197c4a025e11287174adfbfcfe87820ae50c01/packages/docs/package.json#L70C12-L70C20) we can merge it

**Review by gioboa — APPROVED** [review]

**Comment by mgp87** [comment]
> after you run [build.showcase](https://github.com/QwikDev/qwik/blob/81197c4a025e11287174adfbfcfe87820ae50c01/packages/docs/package.json#L70C12-L70C20) we can merge it

Sorry, I am out of home until Sunday

**Comment by gioboa** [comment]
> Sorry, I am out of home until Sunday 

I run the command for you. 😉

**Comment by mgp87** [comment]
Thanks!! ❤️

**Pull request merged**
