### PR TITLE
refactor: Simplify CLI starters

### PR DESCRIPTION
**Pull request by thejackshelton**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
LGTM @thejackshelton

**Comment by thejackshelton** [comment]
> One Test is failing 🥴 Can you check it pls?

Ah yes, was going to tackle this. I still need to test the CLI and get more familiar with it. So converting to draft for now.

**Comment by thejackshelton** [comment]
Ok it's ready for review. I've tested on pkg pr new the three different templates, consuming them with and without dependencies, as well as the dev mode of each.

**Review by gioboa — APPROVED** [review]
Great job 🎉 @thejackshelton

**Pull request merged**
