### PR TITLE
docs(auth): correct @auth/qwik documentation and add migration guide

### LINKED ISSUE #6729: [🐞] @auth/qwik package does not correctly register routes
### Which component is affected?

Qwik Runtime

### Describe the bug

When trying to use the `@auth/qwik` package, routes are not getting registered which causes auth redirects to fail with the error `/api/auth/signin` not found.

image

### Reproduction

https://stackblitz.com/edit/qwik-starter-7tnnx2

### Steps to reproduce

1. Create a new Qwik app
2. Add auth
3. Convert to using `@auth/core` instead of `@builder.io/qwik-auth` in `plugin@auth.ts`.
4. Add an onRequest handler to redirect if a user is unauthenticated

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @auth/core: ^0.13.0 => 0.13.0 
    @auth/qwik: ^0.2.2 => 0.2.2 
    @builder.io/qwik: ^1.4.3 => 1.4.3 
    @builder.io/qwik-auth: 0.1.1 => 0.1.1 
    @builder.io/qwik-city: ^1.4.3 => 1.4.3 
    typescript: 5.3.3 => 5.3.3 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by cwoolum**
fixes #6729

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

The new `@auth/qwik` package has different routes than the original `@builder.io/qwik-auth` package. In the new package, the routes are no longer prefixed with `/api`. This can lead to confusion when the user tries to gate pages and gets redirected to a 404.

# Use cases and why

- 1. Applies to any users that use Auth and are attempting to migrate to the new `@auth/qwik` package.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [N/A] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by cwoolum** [comment]
@gioboa , should I also add an alert or warning that notifies users that are upgrading that the routes changed? I think this change might be easy to miss.

**Comment by gioboa** [comment]
👍 that's a great idea. You can add a note for the users that are upgrading

**Review by gioboa — DISMISSED** [review]
Thanks @cwoolum

**Comment by cwoolum** [comment]
@gioboa , I added some guidance as well as a couple diffs to help others easily migrate 🙂

**Review by gioboa — APPROVED** [review]
Thanks it looks great to me

**Review by gioboa — APPROVED** [review]

**Pull request merged**
