### PR TITLE
docs: improved component$ overview

### PR DESCRIPTION
**Pull request by shairez**
Co-authored-by: Yoav Ganbar <hamatoyogi@users.noreply.github.com>
Co-authored-by: Dmitry Fleish <fleish80@users.noreply.github.com>

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

We've changed the component$ overview doc to be more beginner friendly
The doc now can be used as a reference to how to create simple components without all of mental model explanation that belong in more advanced docs. 

We still have the following work to do:

- [ ] Provide links to other related docs

### CODE REVIEW

**Comment by manucorporat** [comment]
LOVE IT!

**Comment by hamatoyogi** [comment]
I think we have 3 more things left to do here @shairez :
1. Links (like you mentioned)
2. extract important stuff from leftovers or delete them completely
3. add caveat about destructuring props (@manucorporat if you can give one sentence about the status that would be helpful)

**Comment by manucorporat** [comment]
I think the only cavenet is to avoid things like things:

```
export const CMP = component$({value = complexDefaultValue()}) => {

});
```

and avoid props destructuring in functional components like:
```
function Cmp({value}) {

}
```
^ we cant optimize this one

**Comment by zanettin** [comment]
I love it @shairez 🙏 It's very clean now! 

One question regarding `storing a reference`: would it make sense to push that to the state section instead?

And another thing (maybe not related to this PR) is, if we want to add smth like this https://beta.reactjs.org/learn.
Like a quick start for all new ppl interested in qwik to get them started. Guess this would cut the questions asked on the discord channels

**Comment by shairez** [comment]
thanks @zanettin !

Good question about the Ref... I'm not sure tbh
@manucorporat @hamatoyogi WDYT?


About the qwik-start 😉
Yes! totally

**Comment by zanettin** [comment]
@shairez the files have been moved an evolved in the past few months. should we create a new PR with the imortant and still missing parts against the new files?

**Comment by wmertens** [comment]
@shairez is this still good to continue?

**Comment by hamatoyogi** [comment]
I think we might need to redo these as some things are outdated.

**Comment by PatrickJS** [comment]
closing since this is very outdated and the docs have been recently updated

**Pull request closed without merging**
