### PR TITLE
docs: site footer + banner changes

### PR DESCRIPTION
**Pull request by thejackshelton**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
That's great @thejackshelton 
Thanks

**Comment by gioboa** [comment]
image

**Comment by shairez** [comment]
Thanks for reviewing @gioboa !

@thejackshelton we need to also add the "special sponsor" section above the fold, let's sync about it today

**Comment by thejackshelton** [comment]
> Thanks for reviewing @gioboa !
> 
> @thejackshelton we need to also add the "special sponsor" section above the fold, let's sync about it today

Sounds good. Will reach out.

**Comment by thejackshelton** [comment]
> That's great @thejackshelton Thanks

Thanks for the review Giorgio!

**Pull request merged**
