### PR TITLE
feat: Add settings to cookbook

### PR DESCRIPTION
**Pull request by nelsonprsousa**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests / types / typos

# Description

A singleton pattern to expose server-side environment variables across solution

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
`import.meta.env` is returning back the env variables as well. So I'm wondering what's the benefit of this approach.

**Comment by nelsonprsousa** [comment]
> `import.meta.env` is returning back the env variables as well. So I'm wondering what's the benefit of this approach.

Aren't those variable read anywhere, including browser?

**Comment by gioboa** [comment]
> > `import.meta.env` is returning back the env variables as well. So I'm wondering what's the benefit of this approach.
> 
> Aren't those variables read anywhere, including browser?

You can use the `VITE_` prefix 

Here is the documentation https://vitejs.dev/guide/env-and-mode#env-files

> image

**Comment by gioboa** [comment]
Thanks @nelsonprsousa for your commitment.
You are helping Qwik so much :heart:

**Pull request closed without merging**
