### PR TITLE
feat(qwik-city): init Fastly adapter

### PR DESCRIPTION
**Pull request by kalebpace**
# Overview

Hi everyone, 

I've initialized a Qwik City adapter for Fastly's Compute@Edge platform based off the Cloudflare adapter. All code for the adapter and e2e usage [lives here](https://github.com/kalebpace/qwikly) and is [deployed here](https://qwik-city-e2e.edgecompute.app/).

There is a decent amount of work still needed to bring the adapter and starter template up to speed for a proper dev server and production deployment. Though, wanted to open this PR early in the process to get feedback and advice on how best to integrate Fastly specific adapter needs (e.g. adding `fastly.d.ts` to the root Qwik project since `@fastly/js-compute` only exposes types for virtual modules like `fastly:env`).

I have additional [work here](https://github.com/kalebpace/qwikly/tree/kpace/fastly-adapter-with-modified-js-compute) that is slightly older, but had the intention of opening a PR into the `@fastly/js-compute` project to address type issues when trying to import functions using static imports, otherwise dynamic imports are needed. Likely the next step to bringing the adapter up to speed.

Thanks in advance for your time, look forward to hearing any feedback!

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @kalebpace for this integration 
[here](https://github.com/BuilderIO/qwik-city-e2e) you can find the e2e suite to test if the integration is completely covered.

**Comment by kalebpace** [comment]
Thanks @gioboa! I'll give this a go soon. 

If I get things working, should I also open a PR into that repo with a link, plus any other changes, to the environment the E2E tests are run against?

**Comment by gioboa** [comment]
@kalebpace do you have any news for this PR?

**Comment by kalebpace** [comment]
@gioboa thanks for checking-in.

Unfortunately the Fastly runtime has a few APIs missing to fully cover the suite. 

I've outlined what is missing here: https://github.com/BuilderIO/qwik-city-e2e/pull/9
And opened an issue with Fastly: https://github.com/fastly/js-compute-runtime/issues/711

Waiting to get some feedback/suggestions on whether the adapter is acceptable in its current state, maybe tagged as experimental, or if I need to put this work on pause and coordinate with Fastly until APIs are implemented.

Happy to hear any thoughts you might have on this!

**Comment by gioboa** [comment]
I think it's better to ship the feature only when is complete. This avoids unpleasant issue for missing features/bugs.

**Comment by gioboa** [comment]
Hi @kalebpace thanks for your help.
Is this PR still valid or is it abandoned?

**Comment by kalebpace** [comment]
It's likely invalid, good to close

**Pull request closed without merging**
