### PR TITLE
feat(docs): cookbook examples for drag and drop

### PR DESCRIPTION
**Pull request by byte-barista**
# What is it?
- Docs 

# Description
Contains Cookbook examples for drag & drop. Connected to the issue: https://github.com/QwikDev/qwik/issues/6958

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I performed a self-review of my own code
- [ ] I added a changeset with `pnpm change`
- [ ] I made corresponding changes to the Qwik docs
- [ ] I added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
image

It looks great to me :clap: 
Thanks @byte-barista and kudos for your first Qwik PR :partying_face:

**Comment by gioboa** [comment]
@shairez you recently implemented drag and drop, can we have your thoughts?

**Comment by shairez** [comment]
LGTM!
great job @byte-barista !! 👏

**Comment by byte-barista** [comment]
Thanks :)

**Pull request merged**
