### PR TITLE
chore: AWS Lambda Adapter: CloudFront, S3 & Function URL

### PR DESCRIPTION
**Pull request by ptz0n**
# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

A more performant and robust AWS Lambda adapter, using S3 and Lambda Function URL origins behind CloudFront.

# Use cases and why

- Simple and flexible stack for deploying Qwik to AWS.
- Less overhead, removing API Gateway.
- Serving static files from S3.

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
@ptz0n is it still valid or is it abandoned?

**Comment by PatrickJS** [comment]
@ptz0n let me know when it's good

**Comment by PatrickJS** [comment]
@ptz0n lets pair on this

**Comment by PatrickJS** [comment]
abandoned. still planned when I have time. we deployed a qwik app a few different ways on aws I just need to document it

**Comment by gioboa** [comment]
Ok, no worries. I close this PR and you can start from scratch with a new PR.
I mean, you can always look at this PR to copy paste things in the new one. 😉

**Pull request closed without merging**
