### PR TITLE
fix(dev): vite base and qrl segment fixes

### PR DESCRIPTION
**Pull request by wmertens**
- fixes nx monorepo path lookup in dev mode
- fix vite prefix for css etc
- fix qrl segment path encoding for windows in dev mode
- only pass parent filename since path is always the same
- simplify resolveId path handling
- change starter to only add service worker in production
- add base url to manifest

### CODE REVIEW

**Comment by frankroc2022** [comment]
How long can this be taken till the pull request is accepted and we can easy use this fix?

This fix does not solve all off my useOn... problems but a lot.

**Comment by wmertens** [comment]
@frankroc2022 it seems in good shape now, I'd just like some more confirmations that it works for everyone

**Comment by gioboa** [comment]
@frankroc2022 in meantime you can use the continuous build created from this PR. We structured a multi steps approval inside of the core team to reduce regressions like the one we had with v1.6.0.
Thanks for your patience.

**Comment by El-Potato-Slayer** [comment]
> @frankroc2022 it seems in good shape now, I'd just like some more confirmations that it works for everyone

@wmertens I've used the continuous build, but I get this error:
image

For reference, I've added a button:
```
<div onClick$={() => console.log('1')}>click me</div>
```

**Comment by nelsonprsousa** [comment]
Just tried this version.

Got the following error:
`Failed to fetch dynamically imported module: http://localhost:5173/%40fsC%3A%5Csrc%5Cgithub%5Cmilkyway%5Cweb%5Cnode_modules%5Cqwik-speak%5Clib/useqwikspeak_resumecontext_6bh92hvek8o.js?_qrl_parent=use-qwik-speak.qwik.mjs`

Here are some logs with `qwikVite({ debug: true })`:

<details>
<summary>Details</summary>

```bash
Qwik Speak Resolved locale: pt
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/pt/app.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/pt/home.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/pt/listing.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/pt/product.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/pt/runtime.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/pt/app.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/pt/home.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/pt/product.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/pt/listing.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/pt/runtime.json
[QWIK PLUGIN: 804] resolveId(824) Start /@fs/C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs { from:
 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(824) Not resolved /C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs C:/src/github/milkyway/web/index.html
[QWIK PLUGIN: 804] resolveId(825) Start /@fs/C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs { from:
 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(825) Not resolved /C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs C:/src/github/milkyway/web/index.html
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs
[QWIK PLUGIN: 804] resolveId(826) Start /@fs/C:/src/github/milkyway/web/node_modules/vite/dist/client/env.mjs {
  from: 'C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs',
  for: 'client'
}
[QWIK PLUGIN: 804] resolveId(826) Not resolved /@fs/C:/src/github/milkyway/web/node_modules/vite/dist/client/env.mjs C:/src/github/milkyway/web/node_modules/vite/dist/client/client.mjs
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/node_modules/vite/dist/client/env.mjs
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/node_modules/vite/dist/client/env.mjs
[QWIK PLUGIN: 804] resolveId(827) Start /%40fsC%3A\src\github\milkyway\web\src/root_component_useondocument_p6osfoenwte.js?_qrl_parent=root.tsx { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(827) Resolved C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root_component_useondocument_p6osfoenwte.js from transformedOutputs
[QWIK PLUGIN: 804] resolveId(828) Start /%40fsC%3A\src\github\milkyway\web\src/root_component_useondocument_p6osfoenwte.js?_qrl_parent=root.tsx { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(828) Resolved C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root_component_useondocument_p6osfoenwte.js from transformedOutputs
[QWIK PLUGIN: 804] load() transforming QRL parent C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root.tsx
[QWIK PLUGIN: 804] resolveId(829) Start C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root.tsx { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(829) falling back to default resolver
[QWIK PLUGIN: 804] resolveId(830) Start C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root.tsx { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(830) falling back to default resolver
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/src/root.tsx
[QWIK PLUGIN: 804] resolveId(831) Start /%40fsC%3A\src\github\milkyway\web\node_modules\qwik-speak\lib/useqwikspeak_resumecontext_6bh92hvek8o.js?_qrl_parent=use-qwik-speak.qwik.mjs { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(831) Resolved C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/useqwikspeak_resumecontext_6bh92hvek8o.js from transformedOutputs
[QWIK PLUGIN: 804] resolveId(832) Start /%40fsC%3A\src\github\milkyway\web\node_modules\qwik-speak\lib/useqwikspeak_resumecontext_6bh92hvek8o.js?_qrl_parent=use-qwik-speak.qwik.mjs { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(832) Resolved C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/useqwikspeak_resumecontext_6bh92hvek8o.js from transformedOutputs
[QWIK PLUGIN: 804] load() transforming QRL parent C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/use-qwik-speak.qwik.mjs
[QWIK PLUGIN: 804] resolveId(833) Start C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/use-qwik-speak.qwik.mjs { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(833) falling back to default resolver
[QWIK PLUGIN: 804] resolveId(834) Start C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/use-qwik-speak.qwik.mjs { from: 'C:\\src\\github\\milkyway\\web\\index.html', for: 'client' }
[QWIK PLUGIN: 804] resolveId(834) falling back to default resolver
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/@fsC:/src/github/milkyway/web/node_modules/qwik-speak/lib/use-qwik-speak.qwik.mjs
Qwik Speak warn Locale not resolved. Fallback to default locale: en
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/en/app.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/en/home.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/en/listing.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/en/product.json
[QWIK PLUGIN: 804] load() Not found C:/src/github/milkyway/web/i18n/en/runtime.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/en/product.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/en/listing.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/en/app.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/en/home.json
[QWIK PLUGIN: 804] transform() Not transforming C:/src/github/milkyway/web/i18n/en/runtime.json
15:02:30 [vite] Internal server error: Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237
      at AsyncFunction.QwikCityProvider_component_TxCFOy819ag [as resolved] (C:\src\github\milkyway\web\node_modules\@builder.io\qwik-city\index.qwik.mjs:659:11)
      at AsyncFunction.invokeApply (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:3665:22)
      at AsyncFunction.invoke (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:3658:22)
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:7297:21
      at maybeThen (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:384:54)
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:7289:25
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1043:25
      at safeCall (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:373:21)
      at executeComponent (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1043:10)
      at renderSSRComponent (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1405:20)
Qwik Speak warn Locale not resolved. Fallback to default locale: en
15:02:30 [vite] Internal server error: Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237
      at AsyncFunction.QwikCityProvider_component_TxCFOy819ag [as resolved] (C:\src\github\milkyway\web\node_modules\@builder.io\qwik-city\index.qwik.mjs:659:11)
      at AsyncFunction.invokeApply (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:3665:22)
      at AsyncFunction.invoke (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:3658:22)
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:7297:21
      at maybeThen (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:384:54)
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:7289:25
      at C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1043:25
      at safeCall (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:373:21)
      at executeComponent (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1043:10)
      at renderSSRComponent (C:\src\github\milkyway\web\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:1405:20) (x2)
```

</details>

**Comment by shairez** [comment]
@wmertens just tested it and it seems like it's fixing the constant error, but when I change something and HMR it goes straight into the following error:
image


And it goes away when I manually refrech...


If it helps, it seems like it's failing to load the segment of an event handler QRL of the following code:

```
      window:onScroll$={() => {
        windowScrolled.value = window.scrollY > 0;
      }}
```

**Comment by wmertens** [comment]
@nelsonprsousa thank you, looks like it's not handling absolute paths in windows correctly. I'll try to fix. 

@shairez is this with qwik-ui?

**Comment by frankroc2022** [comment]
Is it possible to use @wmertens fix commit with npm? Or only with pnpm?

**Comment by wmertens** [comment]
@frankroc2022 [the instructions](https://github.com/QwikDev/qwik/pull/6629#issuecomment-2201091318) literally use npm :-)

`npm i https://pkg.pr.new/@builder.io/qwik@6629`

**Comment by frankroc2022** [comment]
Thx. I did it wrong. 
It fixes all my vite hmr dev problems. Nice!

**Comment by wmertens** [comment]
@nelsonprsousa I think it's fixed for windows now, can you try?

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa I think it's fixed for windows now, can you try?

I tried again but got the same error.

```
"@builder.io/qwik-city@https://pkg.pr.new/@builder.io/qwik-city@6629":
  version: 1.6.0-dev20240704222606
```

Any ideia if this is the correct version?

**Comment by wmertens** [comment]
@nelsonprsousa no the version should have today's date like dev20240708

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa no the version should have today's date like dev20240708

Let me run `yarn cache clear` and check again. I suspected as well 😅

**Comment by nelsonprsousa** [comment]
Yeap, that was it, now I have:
```
"@builder.io/qwik-city@https://pkg.pr.new/@builder.io/qwik-city@6629":
  version: 1.6.0-dev20240708174604
  resolution: "@builder.io/qwik-city@https://pkg.pr.new/@builder.io/qwik-city@6629"
```

But still with same error 🤔

**Comment by wmertens** [comment]
@nelsonprsousa does it still say stuff like `Not found C:/src/github/milkyway/web/@fsC:/src/github/milkyway`? so C: twice in there?

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa does it still say stuff like `Not found C:/src/github/milkyway/web/@fsC:/src/github/milkyway`? so C: twice in there?

Webpage:
```
Failed to fetch dynamically imported module: http://localhost:5173/%40fsC%3A%5Csrc%5Cgithub%5Cmilkyway%5Cweb%5Cnode_modules%5Cqwik-speak%5Clib/useqwikspeak_resumecontext_6bh92hvek8o.js?_qrl_parent=use-qwik-speak.qwik.mjs
```

Console:
```
TypeError: Failed to fetch dynamically imported module: http://localhost:5173/%40fsC%3A%5Csrc%5Cgithub%5Cmilkyway%5Cweb%5Csrc/root_component_useondocument_p6osfoenwte.js?_qrl_parent=root.tsx
```

**Comment by nelsonprsousa** [comment]
Weirdly enough, the first error is this one:
```
Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237
```

Than it just get replaced in like 0.1 seconds

**Comment by wmertens** [comment]
actually, `http://localhost:5173/%40fsC` is wrong, it should say have the @ like `http://localhost:5173/@fsC`, that's a recent commit, but even then it should say ` http://localhost:5173/@fs/C`, so it's still wrong.

**Comment by nelsonprsousa** [comment]
> actually, `http://localhost:5173/%40fsC` is wrong, it should say have the @ like `http://localhost:5173/@fsC`, that's a recent commit, but even then it should say ` http://localhost:5173/@fs/C`, so it's still wrong.

Just deleted node_modules folder.

Got:

```
Failed to fetch dynamically imported module: http://localhost:5173/@fsC%3A%5Csrc%5Cgithub%5Cmilkyway%5Cweb%5Cnode_modules%5Cqwik-speak%5Clib/useqwikspeak_resumecontext_6bh92hvek8o.js?_qrl_parent=use-qwik-speak.qwik.mjs
```

**Comment by frankroc2022** [comment]
Today 2024-07-08 I run npm i https://pkg.pr.new/@builder.io/qwik@6629. Just I run npm list, it showed:
 @builder.io/qwik@1.6.0-dev20240704222606

Then I changed in package.json
"@builder.io/qwik": "https://pkg.pr.new/@builder.io/qwik@6629",
to 
"@builder.io/qwik": "https://pkg.pr.new/@builder.io/qwik@6629#dc466d6", (latest commit so far)

Now npm list shows:
@builder.io/qwik@1.6.0-dev20240708174604

I rechecked it. With both commits after run npm run dev I get the error:
"error loading dynamically imported module"
but If I then change my code and hmr refrehes page the error is gone and I can change my code how often I want.
To be clear I only have the problem once after enter npm run dev.

I get this error for [...catchall] and without [...catchall].

**Comment by wmertens** [comment]
@frankroc2022
> "error loading dynamically imported module"
look in your browser console for errors like "outdated optimized dep", and maybe add those modules to optimizeDeps.exclude

**Comment by frankroc2022** [comment]
"error loading dynamically imported module: http://localhost:5173/src/components/ts/global_component_useondocument_1nxsaijurq4.js?_qrl_parent=global.tsx"

console:
http://localhost:5173/src/components/ts/global_component_useondocument_1nxsaijurq4.js?_qrl_parent=global.tsx
504 Outdated Optimize Dep

But how I can add my component to:
```
optimizeDeps: {
      // Put problematic deps that break bundling here, mostly those with binaries.
      // For example ['better-sqlite3'] if you use that in server functions.
      exclude: [],
    }
```
?

**Comment by shairez** [comment]
FYI -

Whenever there's a new commit being pushed to a PR, [the commit hash here is being updated](https://github.com/QwikDev/qwik/pull/6629#issuecomment-2201091318)

That means that **you can install the latest commit** by replacing the number suffix (6629) with the commit hash like this:

```
https://pkg.pr.new/@builder.io/qwik@dc466d6
```

**Comment by wmertens** [comment]
@nelsonprsousa can you test the latest update? 

@frankroc2022 can you look into global.tsx, are you importing anything there?

**Comment by wmertens** [comment]
@nelsonprsousa that's utterly bizarre. Can you check the package.json, and/or recreate node_modules to be sure?
The build artifact looks correct to me...

**Comment by jessezhang91** [comment]
I've also been having this problem non-stop the last few days but updated my package.json to use the latest commit from this PR:
```
    "@builder.io/qwik": "https://pkg.pr.new/@builder.io/qwik@f086139",
    "@builder.io/qwik-city": "https://pkg.pr.new/@builder.io/qwik-city@f086139",
```
seems to have fully resolved it! Thanks a bunch!

re: `@builder.io/qwik-city/vite`, I had an issue with that when I only had the qwik package locked to the commit. Once I added qwik-city as well, that went away.

**Review by shairez — APPROVED** [review]

**Comment by nelsonprsousa** [comment]
yarn cache killed me again. Sorry @wmertens, it is working now as expected 🚀 
Thank you!

**Comment by frankroc2022** [comment]
> @nelsonprsousa can you test the latest update?
> 
> @frankroc2022 can you look into global.tsx, are you importing anything there?

I have still the same problem even with 1.7.0.

global.tsx
`import { $, component$, Resource, useContext, useOnDocument, useResource$, useStore, useStylesScoped$ } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import styles from '../navigation/navigation-overlay.css?inline';
import { Image } from "@unpic/qwik";
import { GlobalContext } from '~/routes/layout';

export default component$(() => {
  useStylesScoped$(styles);

  useOnDocument(
    'DOMContentLoaded',
    $(() => {
      console.log('global - document - DOMContentLoaded');

      // if (pathname) {
      //   const url = location.url.href;
      //   const hash = window.location.hash.split('#').pop();

      //   if (!hash) {
      //     window.location.href = location.url.href += '#kontent';
      //     history.replaceState(null, '', url);
      //   }

      // }
    })
  ) 
...`

Error in Firefox 127.0.2 (64-bit) Linux in Oracle VM VirtualBox for Windows 11:
http://localhost:5173/src/components/ts/global_component_useondocument_1nxsaijurq4.js?_qrl_parent=global.tsx
504 Outdated Optimize Dep

The error comes only after npm run dev, after refresh page the error is gone.

The error only exist for useOnDocument with DOMContentLoaded but not for useOnDocument scroll.
The error only exist for useOnWindow with load but not for useOnWindow resize.

Here my package.json:
`{
  "name": "my-qwik-basic-starter",
  "description": "Demo App with Routing built-in (recommended)",
  "engines": {
    "node": "^18.17.0 || ^20.3.0 || >=21.0.0"
  },
  "engines-annotation": "Mostly required by sharp which needs a Node-API v9 compatible runtime",
  "private": true,
  "trustedDependencies": [
    "sharp"
  ],
  "trustedDependencies-annotation": "Needed for bun to allow running install scripts",
  "type": "module",
  "scripts": {
    "build": "qwik build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.server": "vite build -c adapters/netlify-edge/vite.config.ts",
    "build.types": "tsc --incremental --noEmit",
    "deploy": "netlify deploy --build",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "start": "vite --open --mode ssr",
    "qwik": "qwik"
  },
  "devDependencies": {
    "@builder.io/qwik": "^1.7.0",
    "@builder.io/qwik-city": "^1.7.0",
    "@netlify/edge-functions": "^2.9.0",
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.14.10",
    "@typescript-eslint/eslint-plugin": "^7.16.0",
    "@typescript-eslint/parser": "^7.16.0",
    "@unpic/qwik": "^0.0.46",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-qwik": "^1.7.0",
    "netlify-cli": "^17.33.0",
    "postcss": "^8.4.39",
    "prettier": "^3.3.2",
    "prettier-plugin-tailwindcss": "^0.6.5",
    "tailwindcss": "3.4.4",
    "typescript": "5.5.3",
    "undici": "*",
    "vite": "^5.3.3",
    "vite-tsconfig-paths": "^4.3.2"
  },
  "dependencies": {
    "@babel/runtime": "^7.24.7",
    "@netlify/functions": "^2.8.1",
    "intl-segmenter-polyfill": "^0.4.4"
  }
}
`

**Comment by frankroc2022** [comment]
> Thx. I did it wrong. It fixes all my vite hmr dev problems. Nice!
> 
> But what triggered these problems qwik or browser changes? I had these problems also with qwik v.1.5.7 and many other versions I tested.

This was my mistake. I never downgraded to 1.5.7 or older because of my mistake in package.json, I had:
^1.5.7
but it had to be ~1.5.7. Sry for that. For me 1.5.7 was the last working version.

Error since then:
"error loading dynamically imported module"

In 1.6.0 when site auto refreshes.

In 1.7.0 only when site is loaded for the first time.

**Comment by frankroc2022** [comment]
1.7.1 solved all my problems, thx!

**Comment by njoguamos** [comment]
1.7.1 works

**Pull request merged**
