### PR TITLE
docs: update the location of  the re-loader to be under /(qwik-cty) instead of  /cookbook

### PR DESCRIPTION
**Pull request by Kampouse**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos
- [ ] Infra
fix: #6697 
# Description

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have ran `pnpm change` and documented my changes
- [x] I have made corresponding changes to the Qwik docs
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — CHANGES_REQUESTED** [review]
@Kampouse Thanks.
You deleted the cookbook and now there isn't a file in this path 
`/docs/(qwikcity)/re-exporting-loaders/index.mdx`
am I missing something?

**Comment by Kampouse** [comment]
@gioboa  fixed the file was not tracked by github but worked localy 😅

**Review by gioboa — APPROVED** [review]
Thanks @Kampouse

**Comment by brandonpittman** [comment]
https://qwik.dev/docs/cookbook/re-exporting-loaders/

This shows up when searching the docs site but ends in a 404.

**Pull request merged**
