### PR TITLE
feat: vercel serverless

### PR DESCRIPTION
**Pull request by adamdbradley**

### CODE REVIEW

**Comment by zanettin** [comment]
anything missing @adamdbradley ? 🚀

**Comment by mrhoodz** [comment]
You rock @adamdbradley  🙌

**Comment by mhevery** [comment]
@adamdbradley is busy with another project. Can we just test and land this? Happy to help with it.

**Comment by maiieul** [comment]
Happy to help as well!

I think it's an important feature as qwik developers who use auth.js and don't have a database deployed to the edge (which is usually the case for starters) will experience extra latency. 

@mhevery is there anything blocking?

**Comment by mhevery** [comment]
Last I checked with @adamdbradley this was not finished/tested. Hence draft. It would require someone to get the last mile. Mainly do the testing/docs to make sure all is working.

**Comment by PatrickJS** [comment]
I'm going to work with someone to redo this PR and update it

**Comment by PatrickJS** [comment]
we're redoing this here https://github.com/QwikDev/qwik/pull/6355

**Pull request closed without merging**
