### PR TITLE
Caution advised - Package.json docs.dev Windows support 

### PR DESCRIPTION
**Pull request by Shane-Donlon**
# What is it?

- Bug

# Description

See [issue 7175](https://github.com/QwikDev/qwik/issues/7175)
**This has only been tested in Windows**

There may be a few Pull Requests about this topic.
I will keep issue 7175 up to date, but I need to test all the commands etc... 

This resolves issue 1 & issue 4(also see comments  of issue 7175 for localhost confirmation)

Issue 1:
```terminal 
112.3 error: failed to compile `wasm-pack v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-install2iOZDd`.
112.3 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
112.3
112.3 Caused by:
112.3   package `clap_derive v4.5.18` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
```

Issue 4:
the && with CD is not compatible with windows, migrated to concurrently.
This has only been tested in windows.
```terminal
> qwik-monorepo@0.0.0-read-qwik-package-json docs.dev {location of stuff}\qwik
> cd packages/docs && pnpm build.repl-sw && pnpm dev

cd: no such file or directory: packages/docs
```

Note a changeset didn't seem appropriate for this PR, as the options were only files I had not changed,

PS any feedback, please feel free to pass it along! 

# Checklist

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I performed a self-review of my own code
- [ ] I added a changeset with `pnpm change`
- [ ] I made corresponding changes to the Qwik docs
- [ ] I added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
I can test it on Linux Ubuntu and MacOS

**Comment by wmertens** [comment]
Hmm actually we use

$ rustc --version
rustc 1.83.0-nightly (fb4aebddd 2024-09-30)

I don't understand how 0.74 non-nightly can work, we use unstable features which are only available in nightly

See the file `rust-toolchain`

**Comment by Shane-Donlon** [comment]
Hey Wout,

Update from the `rust-toolchain` file.

```
nightly-2024-10-01
```

I did revert the `rust-toolchain` file to `nightly-2024-07-01` and the Dockerfile to `FROM cimg/rust:1.73-node` and that combination allows me to build.

It seems that 

- `nightly-2024-10-01` && `rust1.73` build failed
- `nightly-2024-07-01` && `rust1.73` build succeeded
- `nightly-2024-10-01` && `rust1.74` build succeeded

**Comment by Shane-Donlon** [comment]
Hey everyone,
So I realised I had ran the incorrect command.

But I do have an update.

`nightly-2024-07-01` & `FROM cimg/rust:1.73-node` produced the below error for me.


Command executed:
```terminal
devcontainer up --workspace-folder .
```


```terminal
471.4 error: failed to compile `wasm-pack v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-installTRXqCz`.
471.4 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
471.4
471.4 Caused by:
471.4   package `clap_lex v0.7.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
------
```

`nightly-2024-07-01` & `FROM cimg/rust:1.74-node`

- Successfully built the docker container.

`nightly-2024-10-01` & `FROM cimg/rust:1.74-node`

- Successfully built the docker container.

`nightly-2024-10-01` & `FROM cimg/rust:1.73-node`

- Did not build.
- package `clap_derive v4.5.18` cannot be built error

`nightly-2024-07-01` & `FROM cimg/rust:1.73-node`
- Did not build.
-   package `clap_lex v0.7.2` cannot be built error

**Comment by Shane-Donlon** [comment]
Absolutely, I was trying to explain why I requested a version bump in my PR from 1.73 to 1.74 in the Dockerfile.

Issue 7175 is to explain some of the challenges and errors, I faced going through the instructions.
This request is to try and resolve some of the errors.

The version of Rust I have installed locally is from the link in the contributing document.

```terminal
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-2024-07-01-x86_64-pc-windows-msvc
nightly-2024-10-01-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```

**Comment by Shane-Donlon** [comment]
Hey Gio, Wout, Irfan,
Closing this as a duplication of effort.

Sorry to be dragging everyone in, I know Github sends a lot of emails 😢 

But I did just wanted to take a moment to align on this.
Wout appears to be taking the lead on this with @iitzIrFan in PR https://github.com/QwikDev/qwik/pull/7201

@ everyone 

- see also Issue https://github.com/QwikDev/qwik/issues/7175 if possible to use this issue as a central point for Win OS compatibility issues.

- If there's anything I can do / test / help with etc... add a comment to the issue / tag me and I'll get the notification.

But for now - I am going to take a step away from this.
Have a great day everyone.

Thanks,
Shane

**Comment by gioboa** [comment]
Thanks for your help @Shane-Donlon

**Pull request closed without merging**
