### PR TITLE
docs: Improve theme management section

### PR DESCRIPTION
**Pull request by nelsonprsousa**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests / types / typos

# Description

Improving the theme management section by using new hooks not available at the time.

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by nelsonprsousa** [comment]
This is still a draft PR. However, I'd like to receive some feedback here regarding this changes. The current Theme Management section looks a little bit weird.

What do you guys think and what do you think we could improve here?
cc @thejackshelton @gioboa @mhevery

**Comment by thejackshelton** [comment]
> This is still a draft PR. However, I'd like to receive some feedback here regarding this changes. The current Theme Management section looks a little bit weird.
> 
> What do you guys think and what do you think we could improve here? cc @thejackshelton @gioboa @mhevery
> 
> Also, is there a preview of the website available? It would help checking how this section is rendered with this changes.

You can run the docs site with `pnpm docs.dev`. Have to head out right now, if someone else could take a look.

**Review by gioboa — CHANGES_REQUESTED** [review]
Can you use CodeSandbox and CodeFile components pls?
You can check the other examples that are using
```
import CodeSandbox, {CodeFile} from '../../../../components/code-sandbox/index.tsx';
```
Using these components improve consistency because it's real working code.

**Comment by gioboa** [comment]
hi @nelsonprsousa is it still a valid PR?

**Comment by nelsonprsousa** [comment]
> hi @nelsonprsousa is it still a valid PR?

Yes it yes. It it's still on my TODOs, I just got the flu and need some more time to properly recover before giving this PR some love.

**Comment by gioboa** [comment]
Thanks @nelsonprsousa  best wishes for a speedy recovery

**Comment by jd-michal-popek** [comment]
The sun and moon theme switch is comes from https://github.com/argyleink/gui-challenges/tree/main/theme-switch ([demo](https://gui-challenges.web.app/theme-switch/dist/)), maybe worth mentioning it somewhere?

**Comment by Varixo** [comment]
The sun and moon theme switch is comes from https://github.com/argyleink/gui-challenges/tree/main/theme-switch ([demo](https://gui-challenges.web.app/theme-switch/dist/)), maybe worth mentioning it somewhere?

**Comment by nelsonprsousa** [comment]
> The sun and moon theme switch comes from https://github.com/argyleink/gui-challenges/tree/main/theme-switch ([demo](https://gui-challenges.web.app/theme-switch/dist/)), maybe worth mentioning it somewhere?

Oh yes. I've used the current sun and moon from the docs (https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/components/theme-toggle/sun-and-moon.tsx) but looks like it indeed comes from there.

I'll leave a reference in the docs once I refactor it 👍

**Comment by wmertens** [comment]
@nelsonprsousa still interested in finishing this PR?

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa still interested in finishing this PR?

I am. @thejackshelton told me about some issues with this approach, I still need to dig into that first.

**Comment by PatrickJS** [comment]
@thejackshelton @nelsonprsousa should we redo this PR?

**Comment by nelsonprsousa** [comment]
> @thejackshelton @nelsonprsousa should we redo this PR?

I ended up with a similar solution. I'll try to update this PR in the next 2 days.

**Pull request closed without merging**
