### PR TITLE
chore: add hypecode to showcase

### PR DESCRIPTION
**Pull request by hypecode-tech**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by hypecode-tech** [comment]
https://hypecode.tech has been added.

**Comment by wmertens** [comment]
@hypecode-tech nice! What do you use for i18n?

**Review by wmertens — APPROVED** [review]

**Comment by shairez** [comment]
Look like the performance score could be improved both on desktop and on mobile, can you improve the CLS?
we're looking for a minimum 90 score (95 and above preferred)

(we're also contacting the current websites that have a below 90 score as well and will be removing the unchanged ones)

**Review by gioboa — CHANGES_REQUESTED** [review]
image

@hypecode-tech Would you like to try to improve the site's performance? otherwise we can't perform the merge

**Comment by gioboa** [comment]
Closed by #6849

**Pull request closed without merging**
