### PR TITLE
fix(v2): only wrapped signal as a subscriber

### PR DESCRIPTION
**Pull request by Varixo**
Only WrappedSignal should be a subscriber. Signal and ComputedSingal shoudn't

### CODE REVIEW

**Review by wmertens — COMMENTED** [review]
@Varixo we don't need extra tests for this? And is a ComputedSignal a WrappedSignal?

**Comment by Varixo** [comment]
> @Varixo we don't need extra tests for this? And is a ComputedSignal a WrappedSignal?

there is already a test for cleaning effectdependencies/subscribers. I wonder how we can test it more

And yes in JSX ComputedSignal is a WrappedSignal.

Maybe I am wrong and all signal should be a subscribers?

**Comment by wmertens** [comment]
nono, not all signals need to be subscribers.

**Review by wmertens — APPROVED** [review]
LGTM

**Pull request merged**
