### PR TITLE
docs: inital version of the Brand page 

### PR DESCRIPTION
**Pull request by Kampouse**
# What is it?
#6195   inital version of the brand page!
image

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos
- [ ] Infra

# Description
added the brand page and a link in the footer

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have ran `pnpm change` and documented my changes
- [x] I have made corresponding changes to the Qwik docs
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by PatrickJS — APPROVED** [review]

**Review by PatrickJS — APPROVED** [review]

**Comment by Kampouse** [comment]
removed some local change that should not be here

**Review by thejackshelton — CHANGES_REQUESTED** [review]
Great start!

If we could remove the multiple h1's, since I think that is an SEO content hierarchy issue

An idea, maybe each logo gets downloaded when clicking on it? Or buttons beside each to download it with png or svg?

As for the color, clicking on each color copies that color. similar to https://tailwindcss.com/docs/customizing-colors

**Comment by Kampouse** [comment]
@thejackshelton   Wanted to see  if was going in the right direction before adding js 😄 !
 took good inspiration from the solid 
thanks!
https://www.solidjs.com/media

**Comment by Kampouse** [comment]
made all the element clickable 
image
and  made sur element are visible with acessibity   tool

**Review by maiieul — DISMISSED** [review]
Great start indeed!

Could you add some space between logos section and navbar and footer? 

Astro has a nice page for this https://astro.build/press/

~~Also I prefer `/press`~~ edit: I prefer `/brand` 🙈 doesn't matter too much ^^

Also having a "download all" button like Astro would help for the space between logos and footer. Makes it more harmonious and useful too.

Also using Cards to separate each item would make this look awesome. You could use the qwik-ui styled copy/paste Card component for this.

Please don't hesitate to reach out if you encounter any roadblocks.

Thanks for doing this @Kampouse!

**Comment by wmertens** [comment]
@Kampouse don't forget about this, it would be a very nice addition :)

apart from the issues Maiieul found, for me the UWU version is squashed on wider views.

**Comment by Kampouse** [comment]
image
updated the page to be easier to mess with  look into the card components in qwikui added the  dowload all and some  padding  in y axis  the uwu look more consistent now ...

**Comment by Kampouse** [comment]
image
let me know if anything to update

**Review by PatrickJS — APPROVED** [review]

**Pull request merged**
