### PR TITLE
docs: adding visual clue in the docs TOC

### PR DESCRIPTION
**Pull request by Kampouse**
# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description
adding a viusal clue  same thing as what next docs or qwikUI has 
image

# Use cases and why

improve readabilty in the docs 
# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
@Kampouse are you still working on this?

**Comment by Kampouse** [comment]
got the thing working   i had such  hurdle with the dev server not being responsive (having to  quit it and reload it) 
but the feature should work now

**Review by gioboa — CHANGES_REQUESTED** [review]
Thanks for you commitment @Kampouse 
I fixed few things
I noticed this strange CSS behavior 
image
Can you fix it pls?

**Comment by Kampouse** [comment]
@gioboa  updated the css !

**Review by gioboa — APPROVED** [review]
it works great :clap:

**Pull request merged**
